---
title: "Tidy Tuesday: US National Parks Visits Safer Parks Dataset"
author: "KGJ"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
list_of_packages <- c("janitor", "tidyverse", "lubridate", "ggthemes", "RColorBrewer", "rvest")
lapply(list_of_packages, library, character.only = TRUE)
```


## Quick look at White House Visits by Presidential Term
```{r get_data}
park_visits <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/national_parks.csv")
presidents <- readr::read_csv("https://gist.githubusercontent.com/namuol/2657233/raw/74135b2637e624848c163759be9cd14ae33f5153/presidents.csv")
#thanks to https://gist.github.com/namuol
```


```{r wrangle }

presidents$year_start <- as.numeric(str_sub(presidents$`Took office`, start= -4) ) -1
presidents$year_end <- as.numeric(str_sub(presidents$`Left office`, start= -4) ) - 1

presidents$date_start <- dmy(presidents$`Took office` ) 
presidents$date_end <- dmy(presidents$`Left office`)

presidents[presidents$President =="Barack Obama",]$date_end <- ymd("20161231")
presidents$Number_name <- paste(presidents$Presidency, "-", word(presidents$President,-1) )

presidents <- presidents %>%
  filter(year_start >  1950)

WH_park_visits <- park_visits %>%  
  filter(parkname == "White House") %>%
  filter(year != "Total")

WH_park_visits$year <- as.numeric(WH_park_visits$year)
WH_park_visits$mid_year <- ymd(paste0(WH_park_visits$year,"/06/30"))
```

```{r plot}
WH_park_visits %>%
  ggplot() + 
  geom_rect(data = presidents, aes(xmin = date_start, xmax = date_end, ymin = -Inf, ymax = Inf, fill = Number_name), alpha = 0.4) +
  geom_line(mapping = aes(x = mid_year, y = visitors)) +
  geom_vline(xintercept=ymd("20010911"), linetype="dotted") +
  geom_text(aes(x=(ymd("20010911")), label="Sept 11, 2001", y=1700000),nudge_x= 1900) +
  ggtitle(label = "White House National Park Visits",
          subtitle = "by Presidential Term, 1954-2016") +
  labs(caption = "Source: dataisplural/data.world | gist.github.com/namuol, h/t  tidytuesday") +
  scale_y_continuous(name="Vistors", labels = scales::comma) +
  scale_fill_viridis_d(name  ="President",option = "inferno")+
  scale_x_date(name="Year", limits = c(ymd("19530101"), ymd("20161231")), expand = expand_scale(mult = c(0.01, 0.01)), date_breaks = "4 year", date_labels = "%Y" ) +
      theme(legend.position="bottom", plot.subtitle = element_text(face = "italic"))

```


